version: '3'
services:
  browserless:
    image: browserless/chrome:latest
    ports:
      - '3000:3000'
    environment:
      - MAX_CONCURRENT_SESSIONS=10

  cpami-robot:
    image: mdyu1000/cpami-robot:lastest
    environment:
      - NODE_ENV=production
      - CPAMI_ID=yourId
      - CPAMI_EMAIL=yourEmail
      - DRAFT_ROW=1
    depends_on:
      - browserless
